### ISSUE TITLE
Supports Github commit suggestions?

### ISSUE THREAD

**Issue by polarathene** [ricardochaves/python-lint#5]
I'm not familiar with Github Actions yet, but I have seen and used the [Github `suggestion`](https://github.blog/2018-11-01-suggested-changes-update/) codefence syntax, which lets PR reviews easily enable the author to apply the changes without copy/paste.

I'm familiar with CI tools having a lint stage/step or some projects having a pre-commit git hook to ensure code sticks to convention. Some tools like [textlint](https://textlint.github.io/) however could be nicer to have brought up as suggestions after the PR is submitted and conditionally applied or discussed instead of overriding the contributors original commit data.

I saw [your article that discusses your creation of this repo](https://dev.to/ricardochaves/python-lint-with-github-actions-2i7p), and you had mentioned "If you use a GitHub suggestion", but I don't see anything that indicates that this project outputs the lint results as commit suggestions for a PR? Were you referring to something else?

**Comment by ricardochaves** [comment]
When I spoke about Github suggestion I wanted to say only about the Github actions. In some place on the documentation (which I cant find right now), they put that for you to create the lint you need to do something like I wrote in my article and I made this repo just for abstracting some things.

I don't want to produce the same result as textlint (I didn't know this tool, it is very nice), my idea is to just create a first defense for PRs.

**Comment by peternewman** [comment]
I assume @polarathene was more meaning it could offer annotations or comments with suggested fixes, rather than forcing the user to do it manually.

FWIW @polarathene , when I looked at this before it doesn't seem very easy to do suggestions (compared to annotations, or even as part of them). From what I can tell they are only possible in comments. The only options I found before, which both suggest they may have flaws, are:
https://github.com/marketplace/actions/action-git-diff-suggestions
https://github.com/marketplace/actions/reviewdog-suggester-suggest-any-code-changes-based-on-diff-with-reviewdog
